# Site wide configuration
destination: docs
url: 'https://trianglesitedesign.com'
baseurl: ''
locale: en

# Analytics
google_analytics_measurement_id: G-LMP1W6MCQB

# Jekyll configuration
version: v1.2.0
permalink: /:categories/:title/
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
include:
  - _pages
exclude:
  - .bundle
  - .jekyll-cache
  - .gitignore
  - .project
  - _drafts
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - Photoshop/
  - vendor/bundle/

excerpt_separator: <!--more-->

sass:
  style: :compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

# Use the following plug-ins
gems:
  - jekyll-feed
  - jekyll-liquify
  - jekyll-paginate-v2
  - jekyll-sitemap

# Plugin: Pagination (jekyll-paginate-v2)
pagination:
  enabled: true
  per_page: 3
  permalink: '/:num/'
  title: ':title | :num of :max'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  trail: 
    before: 2
    after: 2

# Plugin: Auto Pages (jekyll-paginate-v2)
autopages:
  enabled: false
  tags:
    enabled: true
    layouts:
      - autopage_tags.html
    permalink: /tag/:tag
  categories:
    enabled: false
    layouts:
      - autopage_category.html
  collections:
    enabled: false
    slugify:
      mode: 'ascii'
      cased: true